- id: prism
  name: prism
  description: "Prism: The uncompromising Python code formatter"
  entry: prism
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]
- id: prism-jupyter
  name: prism-jupyter
  description:
    "Prism: The uncompromising Python code formatter (with Jupyter Notebook support)"
  entry: prism
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi, jupyter]
  additional_dependencies: [".[jupyter]"]
